version: '3.8'

services:
  ethereum-node:
    image: ethereum/client-go:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data:/data
      - ./pwd.txt:/pwd.txt
    entrypoint: >
      sh -c "
        if [ ! -f /data/keystore/created ]; then
          geth account new --datadir /data --password /pwd.txt;
          touch /data/keystore/created;
        fi &&
        geth --dev --datadir /data --password /pwd.txt
      "
